stages:
  - build

build-code:
  stage: build
  image: maven
  tags:
  - shell_reg
  script:
  - echo "==== Project Building Started ====="
  - mvn clean install
  - echo "code build Successfull..."
  - pwd
  - ls
  when: always
  artifacts:
    paths:
      - target/*.war
    expire_in: 15 days

 